// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/itk13201/money-rabbit/ent/category"
	"github.com/itk13201/money-rabbit/ent/categoryrule"
)

// CategoryRuleCreate is the builder for creating a CategoryRule entity.
type CategoryRuleCreate struct {
	config
	mutation *CategoryRuleMutation
	hooks    []Hook
}

// SetKeyword sets the "keyword" field.
func (_c *CategoryRuleCreate) SetKeyword(v string) *CategoryRuleCreate {
	_c.mutation.SetKeyword(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *CategoryRuleCreate) SetPriority(v int) *CategoryRuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *CategoryRuleCreate) SetNillablePriority(v *int) *CategoryRuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CategoryRuleCreate) SetID(v uuid.UUID) *CategoryRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CategoryRuleCreate) SetNillableID(v *uuid.UUID) *CategoryRuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_c *CategoryRuleCreate) SetCategoryID(id uuid.UUID) *CategoryRuleCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *CategoryRuleCreate) SetCategory(v *Category) *CategoryRuleCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the CategoryRuleMutation object of the builder.
func (_c *CategoryRuleCreate) Mutation() *CategoryRuleMutation {
	return _c.mutation
}

// Save creates the CategoryRule in the database.
func (_c *CategoryRuleCreate) Save(ctx context.Context) (*CategoryRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CategoryRuleCreate) SaveX(ctx context.Context) *CategoryRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CategoryRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CategoryRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CategoryRuleCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := categoryrule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := categoryrule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CategoryRuleCreate) check() error {
	if _, ok := _c.mutation.Keyword(); !ok {
		return &ValidationError{Name: "keyword", err: errors.New(`ent: missing required field "CategoryRule.keyword"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "CategoryRule.priority"`)}
	}
	if len(_c.mutation.CategoryIDs()) == 0 {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required edge "CategoryRule.category"`)}
	}
	return nil
}

func (_c *CategoryRuleCreate) sqlSave(ctx context.Context) (*CategoryRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CategoryRuleCreate) createSpec() (*CategoryRule, *sqlgraph.CreateSpec) {
	var (
		_node = &CategoryRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(categoryrule.Table, sqlgraph.NewFieldSpec(categoryrule.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Keyword(); ok {
		_spec.SetField(categoryrule.FieldKeyword, field.TypeString, value)
		_node.Keyword = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(categoryrule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   categoryrule.CategoryTable,
			Columns: []string{categoryrule.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.category_rules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CategoryRuleCreateBulk is the builder for creating many CategoryRule entities in bulk.
type CategoryRuleCreateBulk struct {
	config
	err      error
	builders []*CategoryRuleCreate
}

// Save creates the CategoryRule entities in the database.
func (_c *CategoryRuleCreateBulk) Save(ctx context.Context) ([]*CategoryRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CategoryRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CategoryRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CategoryRuleCreateBulk) SaveX(ctx context.Context) []*CategoryRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CategoryRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CategoryRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
