// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/itk13201/money-rabbit/ent/category"
	"github.com/itk13201/money-rabbit/ent/categoryrule"
	"github.com/itk13201/money-rabbit/ent/predicate"
)

// CategoryRuleUpdate is the builder for updating CategoryRule entities.
type CategoryRuleUpdate struct {
	config
	hooks    []Hook
	mutation *CategoryRuleMutation
}

// Where appends a list predicates to the CategoryRuleUpdate builder.
func (_u *CategoryRuleUpdate) Where(ps ...predicate.CategoryRule) *CategoryRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKeyword sets the "keyword" field.
func (_u *CategoryRuleUpdate) SetKeyword(v string) *CategoryRuleUpdate {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *CategoryRuleUpdate) SetNillableKeyword(v *string) *CategoryRuleUpdate {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CategoryRuleUpdate) SetPriority(v int) *CategoryRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CategoryRuleUpdate) SetNillablePriority(v *int) *CategoryRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CategoryRuleUpdate) AddPriority(v int) *CategoryRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *CategoryRuleUpdate) SetCategoryID(id uuid.UUID) *CategoryRuleUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *CategoryRuleUpdate) SetCategory(v *Category) *CategoryRuleUpdate {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the CategoryRuleMutation object of the builder.
func (_u *CategoryRuleUpdate) Mutation() *CategoryRuleMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *CategoryRuleUpdate) ClearCategory() *CategoryRuleUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CategoryRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CategoryRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CategoryRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CategoryRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CategoryRuleUpdate) check() error {
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CategoryRule.category"`)
	}
	return nil
}

func (_u *CategoryRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(categoryrule.Table, categoryrule.Columns, sqlgraph.NewFieldSpec(categoryrule.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(categoryrule.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(categoryrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(categoryrule.FieldPriority, field.TypeInt, value)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   categoryrule.CategoryTable,
			Columns: []string{categoryrule.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   categoryrule.CategoryTable,
			Columns: []string{categoryrule.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{categoryrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CategoryRuleUpdateOne is the builder for updating a single CategoryRule entity.
type CategoryRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CategoryRuleMutation
}

// SetKeyword sets the "keyword" field.
func (_u *CategoryRuleUpdateOne) SetKeyword(v string) *CategoryRuleUpdateOne {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *CategoryRuleUpdateOne) SetNillableKeyword(v *string) *CategoryRuleUpdateOne {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CategoryRuleUpdateOne) SetPriority(v int) *CategoryRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CategoryRuleUpdateOne) SetNillablePriority(v *int) *CategoryRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CategoryRuleUpdateOne) AddPriority(v int) *CategoryRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *CategoryRuleUpdateOne) SetCategoryID(id uuid.UUID) *CategoryRuleUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *CategoryRuleUpdateOne) SetCategory(v *Category) *CategoryRuleUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the CategoryRuleMutation object of the builder.
func (_u *CategoryRuleUpdateOne) Mutation() *CategoryRuleMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *CategoryRuleUpdateOne) ClearCategory() *CategoryRuleUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// Where appends a list predicates to the CategoryRuleUpdate builder.
func (_u *CategoryRuleUpdateOne) Where(ps ...predicate.CategoryRule) *CategoryRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CategoryRuleUpdateOne) Select(field string, fields ...string) *CategoryRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CategoryRule entity.
func (_u *CategoryRuleUpdateOne) Save(ctx context.Context) (*CategoryRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CategoryRuleUpdateOne) SaveX(ctx context.Context) *CategoryRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CategoryRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CategoryRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CategoryRuleUpdateOne) check() error {
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CategoryRule.category"`)
	}
	return nil
}

func (_u *CategoryRuleUpdateOne) sqlSave(ctx context.Context) (_node *CategoryRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(categoryrule.Table, categoryrule.Columns, sqlgraph.NewFieldSpec(categoryrule.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CategoryRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, categoryrule.FieldID)
		for _, f := range fields {
			if !categoryrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != categoryrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(categoryrule.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(categoryrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(categoryrule.FieldPriority, field.TypeInt, value)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   categoryrule.CategoryTable,
			Columns: []string{categoryrule.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   categoryrule.CategoryTable,
			Columns: []string{categoryrule.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CategoryRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{categoryrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
