// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/itk13201/money-rabbit/ent/category"
	"github.com/itk13201/money-rabbit/ent/categoryrule"
	"github.com/itk13201/money-rabbit/ent/schema"
	"github.com/itk13201/money-rabbit/ent/transaction"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescSortOrder is the schema descriptor for sort_order field.
	categoryDescSortOrder := categoryFields[5].Descriptor()
	// category.DefaultSortOrder holds the default value on creation for the sort_order field.
	category.DefaultSortOrder = categoryDescSortOrder.Default.(int)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
	categoryruleFields := schema.CategoryRule{}.Fields()
	_ = categoryruleFields
	// categoryruleDescPriority is the schema descriptor for priority field.
	categoryruleDescPriority := categoryruleFields[2].Descriptor()
	// categoryrule.DefaultPriority holds the default value on creation for the priority field.
	categoryrule.DefaultPriority = categoryruleDescPriority.Default.(int)
	// categoryruleDescID is the schema descriptor for id field.
	categoryruleDescID := categoryruleFields[0].Descriptor()
	// categoryrule.DefaultID holds the default value on creation for the id field.
	categoryrule.DefaultID = categoryruleDescID.Default.(func() uuid.UUID)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescImportedAt is the schema descriptor for imported_at field.
	transactionDescImportedAt := transactionFields[5].Descriptor()
	// transaction.DefaultImportedAt holds the default value on creation for the imported_at field.
	transaction.DefaultImportedAt = transactionDescImportedAt.Default.(func() time.Time)
	// transactionDescID is the schema descriptor for id field.
	transactionDescID := transactionFields[0].Descriptor()
	// transaction.DefaultID holds the default value on creation for the id field.
	transaction.DefaultID = transactionDescID.Default.(func() uuid.UUID)
}
