// Code generated by ent, DO NOT EDIT.

package transaction

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the transaction type in the database.
	Label = "transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldImportFormatID holds the string denoting the import_format_id field in the database.
	FieldImportFormatID = "import_format_id"
	// FieldImportedAt holds the string denoting the imported_at field in the database.
	FieldImportedAt = "imported_at"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// Table holds the table name of the transaction in the database.
	Table = "transactions"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "transactions"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_transactions"
)

// Columns holds all SQL columns for transaction fields.
var Columns = []string{
	FieldID,
	FieldDate,
	FieldDescription,
	FieldAmount,
	FieldImportFormatID,
	FieldImportedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "transactions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"category_transactions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultImportedAt holds the default value on creation for the "imported_at" field.
	DefaultImportedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ImportFormatID defines the type for the "import_format_id" enum field.
type ImportFormatID string

// ImportFormatID values.
const (
	ImportFormatIDSmbcBank ImportFormatID = "smbc_bank"
	ImportFormatIDSmbcCard ImportFormatID = "smbc_card"
)

func (ifi ImportFormatID) String() string {
	return string(ifi)
}

// ImportFormatIDValidator is a validator for the "import_format_id" field enum values. It is called by the builders before save.
func ImportFormatIDValidator(ifi ImportFormatID) error {
	switch ifi {
	case ImportFormatIDSmbcBank, ImportFormatIDSmbcCard:
		return nil
	default:
		return fmt.Errorf("transaction: invalid enum value for import_format_id field: %q", ifi)
	}
}

// OrderOption defines the ordering options for the Transaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByImportFormatID orders the results by the import_format_id field.
func ByImportFormatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportFormatID, opts...).ToFunc()
}

// ByImportedAt orders the results by the imported_at field.
func ByImportedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportedAt, opts...).ToFunc()
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
