// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "color", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"income", "expense", "both"}},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// CategoryRulesColumns holds the columns for the "category_rules" table.
	CategoryRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "keyword", Type: field.TypeString},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "category_rules", Type: field.TypeUUID},
	}
	// CategoryRulesTable holds the schema information for the "category_rules" table.
	CategoryRulesTable = &schema.Table{
		Name:       "category_rules",
		Columns:    CategoryRulesColumns,
		PrimaryKey: []*schema.Column{CategoryRulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "category_rules_categories_rules",
				Columns:    []*schema.Column{CategoryRulesColumns[3]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "date", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt},
		{Name: "import_format_id", Type: field.TypeEnum, Enums: []string{"smbc_bank", "smbc_card"}},
		{Name: "imported_at", Type: field.TypeTime},
		{Name: "category_transactions", Type: field.TypeUUID, Nullable: true},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_categories_transactions",
				Columns:    []*schema.Column{TransactionsColumns[6]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		CategoryRulesTable,
		TransactionsTable,
	}
)

func init() {
	CategoryRulesTable.ForeignKeys[0].RefTable = CategoriesTable
	TransactionsTable.ForeignKeys[0].RefTable = CategoriesTable
}
