{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moneyrabbit.backend.fullname" . }}
  labels:
    {{- include "moneyrabbit.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "%s:%s@tcp(%s:3306)/%s?parseTime=true" .Values.mariadb.auth.username .Values.mariadb.auth.password (include "moneyrabbit.mariadb.fullname" .) .Values.mariadb.auth.database | quote }}
  ANTHROPIC_API_KEY: {{ .Values.backend.anthropicApiKey | quote }}
{{- end }}
